"""added data in tables

Revision ID: 982f1866d9f8
Revises: 
Create Date: 2024-01-20 23:40:38.861828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982f1866d9f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
